//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace App.Web
{
    public partial class Checkout
    {
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
